services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    ports:
      - 8080:8080 
    environment:
      - KC_HOSTNAME=http://localhost:8080
      - KC_HOSTNAME_STRICT_HTTPS='true'
      - KC_TLS_HOSTNAME_VERIFIER=ANY
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin 
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
    volumes:
      - ./keycloak/data:/opt/keycloak/data
    depends_on:
      - postgres
    command: start-dev --import-realm
  
  postgres:
    image: postgres:17
    expose:
      - 5432
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
